spring:
  application:
    name: TM66

upload:
  comment-dir: ${COMMENT_DIR:upload}
  worker-dir: ${WORKER_DIR:worker}

user:
  kgs:
    email: ${KGS_EMAIL:}
    ftp-path: ${KGS_FTP:}

app:
  version: ver.:0.0.10
  ftp:
    host: ${FTP_HOST:}
    port: ${FTP_PORT:}
    user: ${FTP_USER:}
    password: ${FTP_PSW:}